### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ayushmxn** [vitor251093/electron-to-nwjs#1]
I came across this project from GitHub's discover feature and it peaked my interest. Is the goal of the project to convert an Electron app into NW.js app?

**Comment by vitor251093** [comment]
Hello!

Yes, this is the goal of the project.

I had that idea because I need to maintain a complex application, currently coded in Electron, and converting that application to NW.js entirely, just to test if the performance improvement would be worth or not, would be too much work which could go wasted.

So instead, I've created that module, to convert Electron apps into NW.js apps, so I don't need to perform all the changes manually, and in that way, no one is going to need either.

Btw, I just realized you ar eone of the maintainers of nw-builder, is that right? nw-builder has been a blessing. After using webpack to adapt the projects to NW.js, I use nw-builder to run and build them afterwards.

**Comment by ayushmxn** [comment]
> I had that idea because I need to maintain a complex application, currently coded in Electron, and converting that application to NW.js entirely, just to test if the performance improvement would be worth or not, would be too much work which could go wasted.

That's a super interesting! Good luck that :)

> Btw, I just realized you ar eone of the maintainers of nw-builder, is that right? nw-builder has been a blessing. After using webpack to adapt the projects to NW.js, I use nw-builder to run and build them afterwards.

Thanks! I've been maintaining it for a while but only recently started using it recently :P cuz I finally smoothened out the rough edges. Plan to add packaging capability soon so it's easier to distribute to end users.
